### ISSUE TITLE
Issue while building on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by 0x3444ac53** [NerdyPepper/taizen#13]
`linuxpad :: ~/taizen 101 » cargo run --release
   Compiling num-traits v0.2.5
   Compiling unicode-xid v0.1.0
   Compiling version_check v0.1.4
   Compiling maplit v1.0.1
   Compiling adler32 v1.0.3
   Compiling gcc v0.3.54
   Compiling scopeguard v0.3.3
   Compiling bitflags v0.9.1
   Compiling cfg-if v0.1.4
   Compiling strsim v0.7.0
   Compiling lazy_static v0.2.11
   Compiling lazycell v0.6.0
   Compiling vec_map v0.8.1
   Compiling byteorder v1.2.3
   Compiling foreign-types-shared v0.1.1
   Compiling bitflags v1.0.3
   Compiling num-rational v0.2.1
   Compiling fnv v1.0.6
   Compiling cc v1.0.18
   Compiling stable_deref_trait v1.1.0
   Compiling httparse v1.3.2
   Compiling string v0.1.1
   Compiling void v1.0.2
   Compiling urlencoding v1.0.0
   Compiling serde v1.0.70
   Compiling crossbeam-utils v0.4.1
   Compiling matches v0.1.7
   Compiling unicode-width v0.1.5
   Compiling utf8-ranges v1.0.0
   Compiling arc-swap v0.2.0
error[E0658]: slice pattern syntax is experimental (see issue #23121)
   --> /home/adien/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.2.0/src/lib.rs:658:59
    |
658 |             let groups = self.shards.iter().fold([0, 0], |[a1, a2], s| {
    |                                                           ^^^^^^^^

error[E0658]: slice pattern syntax is experimental (see issue #23121)
   --> /home/adien/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.2.0/src/lib.rs:659:21
    |
659 |                 let [v1, v2] = s.snapshot();
    |                     ^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `arc-swap`.
warning: build failed, waiting for other jobs to finish...
error: build failed
linuxpad :: ~/taizen 101 » 
`

**Comment by oppiliappan** [comment]
Which version of `rustc` are you compiling against?

Works fine on Ubuntu 18.04 with `rustc` version `1.26.2`

**Comment by icyphox** [comment]
Even I'm facing this error. I really want to use Taizen but I just can't. 
Please fix.

**Comment by altaaa** [comment]
I built it on 18.04 like this:

```
sudo apt-get install libncursesw5-dev libssl-dev
curl https://sh.rustup.rs -sSf | sh

# log out and back in

cd ~/Downloads
git clone https://github.com/nerdypepper/taizen
cd taizen
cargo run --release
```

**Comment by 0x3444ac53** [comment]
`~ [ cd taizen                                                         ] 3:05 PM
~/taizen [ cargo run --release                                 master ] 3:05 PM
   Compiling arc-swap v0.2.0
   Compiling unicode-width v0.1.5
error[E0658]: slice pattern syntax is experimental (see issue #23121)
   --> /home/adien/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.2.0/src/lib.rs:658:59
    |
658 |             let groups = self.shards.iter().fold([0, 0], |[a1, a2], s| {
    |                                                           ^^^^^^^^

error[E0658]: slice pattern syntax is experimental (see issue #23121)
   --> /home/adien/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.2.0/src/lib.rs:659:21
    |
659 |                 let [v1, v2] = s.snapshot();
    |                     ^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `arc-swap`.
warning: build failed, waiting for other jobs to finish...
error: build failed
~/taizen [ rustc -v                                            master ] 3:05 PM
error: no input filename given

~/taizen [ rustc --version                                     master ] 3:05 PM
rustc 1.25.0
~/taizen [ cargo run --release                                                                                master ] 3:23 PM
   Compiling build_const v0.2.1
   Compiling arc-swap v0.2.0
error[E0658]: slice pattern syntax is experimental (see issue #23121)
   --> /home/adien/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.2.0/src/lib.rs:658:59
    |
658 |             let groups = self.shards.iter().fold([0, 0], |[a1, a2], s| {
    |                                                           ^^^^^^^^

error[E0658]: slice pattern syntax is experimental (see issue #23121)
   --> /home/adien/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.2.0/src/lib.rs:659:21
    |
659 |                 let [v1, v2] = s.snapshot();
    |                     ^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `arc-swap`.
warning: build failed, waiting for other jobs to finish...
error: build failed
~/taizen [ cargo run --release                                                                                master ] 3:23 PM
   Compiling array-macro v1.0.2
   Compiling futures v0.1.23
   Compiling num-rational v0.2.1
   Compiling void v1.0.2
   Compiling openssl v0.9.24
   Compiling unicode-segmentation v1.2.1
   Compiling arc-swap v0.2.0
error[E0658]: slice pattern syntax is experimental (see issue #23121)
   --> /home/adien/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.2.0/src/lib.rs:658:59
    |
658 |             let groups = self.shards.iter().fold([0, 0], |[a1, a2], s| {
    |                                                           ^^^^^^^^

error[E0658]: slice pattern syntax is experimental (see issue #23121)
   --> /home/adien/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.2.0/src/lib.rs:659:21
    |
659 |                 let [v1, v2] = s.snapshot();
    |                     ^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `arc-swap`.
warning: build failed, waiting for other jobs to finish...
error: build failed
~/taizen [                                                                                                    master ] 3:25 PM
`

**Comment by altaaa** [comment]
> error[E0658]: slice pattern syntax is experimental (see issue #23121)

I got this error with rustc 1.25 which is in the Ubuntu repos.

Please try `sudo apt-get remove rustc` and then installing rustc like this:

`curl https://sh.rustup.rs -sSf | sh`

This installed rustc 1.29.2 (17a9dc751 2018-10-05) earlier today for me and I could then build taizen.

**Comment by 0x3444ac53** [comment]
thank you, I suppose I misread the output, because I tried removing the rust package. thank you for the guidance
